Config:
    AWS_PROFILE: default  # Name of your AWS profile from .aws/credentials
    DESTINATION_NAME: SensorAppDestination  # Sidewalk destination used for uplink traffic routing
    HARDWARE_PLATFORM: ALL  # Available values: NORDIC, TI, SILABS or ALL
Outputs:
    DEVICE_PROFILE_ID: null
    WEB_APP_URL: null
_Paths:
    PROVISION_SCRIPT_DIR: tools/provision
    SILABS_COMMANDER_TOOLS_DIR: null  # Not needed if Silabs Commander is already in system Path. Only needed for SILABS.
